/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetablepro;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

public class FeedbackPanel extends javax.swing.JPanel implements ActionListener {
    Color currentColour;
    Timer t;
    TimetablePro tp;
    int alpha;
    boolean correct;

    
    public FeedbackPanel() {
        initComponents();
        t = new Timer(2, this);
        currentColour = Color.white;
       
    }
    public void showFeedback(boolean correct) {
        this.correct = correct;
        currentColour = correct ? Color.GREEN : Color.RED;
        
        alpha = 150;
        t.start();
    }
    public void actionPerformed(ActionEvent e) {
        float[] rgb = currentColour.getRGBColorComponents(null);
        alpha -= 5;
        
        if (alpha < 0) {
            t.stop();
            currentColour = Color.white;
        } else {
            currentColour = new Color(rgb[0], rgb[1], rgb[2], (alpha)/255.0f);
        }
        tp.repaint();
    }
    public void paintComponent(Graphics g){
        g.setColor(currentColour);
        g.fillRoundRect(0,0,this.getWidth(),this.getHeight(), 10, 10);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(timetablepro.TimetablePro.GLOBAL_BG);
        setForeground(timetablepro.TimetablePro.GLOBAL_BG);
        setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    void setMainScreen(TimetablePro tp) {
        this.tp = tp;
    }

    
}
