/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetablepro;

import java.awt.*;

public class NumberPanel extends javax.swing.JPanel {
    static Color BORDER = convertColour(javafx.scene.paint.Color.CHOCOLATE);
    static Color BACKGROUND = convertColour(javafx.scene.paint.Color.BISQUE);
    static int WIDTH = 100, HEIGHT = 50, ARC_AMOUNT = 15;
    static Font FONT = new Font("Segoe UI Semibold", Font.PLAIN, 36);
    public int num = 10;
    /**
     * Creates new form NumberPanel
     */
    public NumberPanel() {
        initComponents();
    }
    @Override
    public Dimension preferredSize() {
        return new Dimension(WIDTH+5, HEIGHT+5);
    }
    public static Color convertColour(javafx.scene.paint.Color c) {
        int[] col = new int[3];
        col[0] = (int)(c.getRed() * 255);
        col[1] = (int)(c.getGreen()*255);
        col[2] = (int)(c.getBlue() *255);
        return new java.awt.Color(col[0], col[1], col[2]); 
    }

    public int get() {
        return num;
    }
    @Override
    public void paintComponent(Graphics g) {
        g.setColor(BACKGROUND);
        g.fillRoundRect(0, 0, WIDTH, HEIGHT, ARC_AMOUNT, ARC_AMOUNT);
        
        g.setColor(BORDER);
        g.drawRoundRect(0, 0, WIDTH, HEIGHT, ARC_AMOUNT, ARC_AMOUNT);
        
        // draw number
        
        if (num == 0) return;
        String text = String.valueOf(num);
        g.setFont(FONT);
        FontMetrics fm = g.getFontMetrics();
        int totalWidth = fm.stringWidth(text);
        
        // absolutely centred
        int x = (WIDTH / 2) - (totalWidth / 2);
        int y = (HEIGHT - fm.getHeight()) / 2 + fm.getAscent(); 
        //x -= fm.stringWidth(text) / 2;
        
        g.setColor(BORDER);
        g.drawString(text, x, y);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(null);
        setForeground(null);
        setEnabled(false);
        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(100, 50));
        setMinimumSize(new java.awt.Dimension(100, 50));
        setPreferredSize(preferredSize());
        setRequestFocusEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
